### ISSUE TITLE
Ecore diagram editor shows import icons on inheritance arrows

### ISSUE THREAD

**Issue by dhendriks** [eclipse-emf/org.eclipse.emf#12]
It looks something like this:

![image](https://github.com/eclipse-emf/org.eclipse.emf/assets/375606/c7799d88-766a-43af-b76e-3de604e6b960)

You can see the import icon on the inheritance arrow in the left diagram. To reproduce:

* Create a new 'Ecore Modeling Project'. Name it `test`. Accept defaults.
* Create a new 'Ecore Model' in the same `model` directory, naming it `test2`.
* Name the package in `test2` also `test2`.
* Add a class diagram representation also for `test2`.
* Add a class named `Class1` to `test` using the diagram editor.
* Add a class named `Class2` to `test2` using the diagram editor.
* Save both diagrams.
* Add each class to the other diagram, using the 'Add' tool from the 'Existing Elements' part of the palette.
* Add an inheritance relation from one class to another, in one of the diagrams, using the 'SuperType' tool.
* Note how in one of the diagram the inheritance arrow shows with an import icon.

I get the import icon on imported classes, and find it useful. But it just looks weird an confusing on the arrow, in my opinion. Especially if you have a tree of inheritance relations, like this example from a metamodel in the Eclipse ESCET project:

![image](https://github.com/eclipse-emf/org.eclipse.emf/assets/375606/a4e3f432-b37a-43ff-a95a-8fdad3733463)

**Comment by merks** [comment]
Please report the issue here

https://github.com/eclipse-ecoretools/ecoretools/issues

I can’t move the issue to another GitHub organization.

**Comment by dhendriks** [comment]
Ah, I did look for other repos, but didn't find that one. I reported it there: https://github.com/eclipse-ecoretools/ecoretools/issues/7
