### ISSUE TITLE
[21] XMLString.removeLast() does not compile

### ISSUE THREAD

**Issue by jukzi** [eclipse-emf/org.eclipse.emf#13]
using JDK 21:
org.eclipse.emf.ecore.xmi.impl.XMLString.removeLast():
```
- overrides java.util.List<org.eclipse.emf.ecore.xmi.impl.StringSegment.Element>.removeLast
- The return type is incompatible with List<StringSegment.Element>.removeLast()
```

**Comment by jukzi** [comment]
making removeLast private and rename it would solve the problem for jdk 21

**Comment by merks** [comment]
That's nasty.  It's a public class that can be extended and that method could be overridden.    Highly unlikely of course...
