### ISSUE TITLE
Ecore and GenModel Editor Property table column too narrow

### ISSUE THREAD

**Issue by Phillipus** [eclipse-emf/org.eclipse.emf#14]
Mac Ventura
Eclipse 4.28

When editing an ecore file or genmodel file the property sheet's first column is too narrow so that the text is clipped. It would help if the column was resizeable, but it isn't.

Example 1
<img width="274" alt="Screenshot 2023-10-01 at 06 38 52" src="https://github.com/eclipse-emf/org.eclipse.emf/assets/600504/918f09bc-cebf-4015-8ed8-6b755b4b1198">

Example 2
<img width="220" alt="Screenshot 2023-10-01 at 06 39 11" src="https://github.com/eclipse-emf/org.eclipse.emf/assets/600504/a05dc905-216a-4830-a5ca-b9a51403b790">  

Example 3
<img width="248" alt="Screenshot 2023-10-01 at 06 40 45" src="https://github.com/eclipse-emf/org.eclipse.emf/assets/600504/715b13ca-6a8f-4b67-b28e-3885b9a5d9f2">

**Comment by merks** [comment]
It works well (sized to fit the property labels) on Windows:

![image](https://github.com/eclipse-emf/org.eclipse.emf/assets/208716/cd13defc-b5e4-4017-a429-9802ca0ae877)

![image](https://github.com/eclipse-emf/org.eclipse.emf/assets/208716/1fadb965-ce51-4bdd-a565-120d8169e735)


I recall a mac bug in the installer also related to auto-resizing of columns.  The bug will be in org.eclipse.emf.common.ui.viewer.ColumnResizer, probably in org.eclipse.emf.common.ui.viewer.ColumnResizer.ColumnResizerHandler.controlResized(ControlEvent).  The setup for contribution is very easy and automated:

https://github.com/eclipse-emf/org.eclipse.emf/blob/master/CONTRIBUTING.md

In fact, if you have the Platform SDK setup already, these source projects will already be in your workspace...

**Comment by Phillipus** [comment]
I had a look at `ColumnResizer` and I could see that there's a magic width offset of 10:

https://github.com/eclipse-emf/org.eclipse.emf/blob/fc18f373ecc2fa11c53f77fbc5b26f01cd03982b/plugins/org.eclipse.emf.common.ui/src/org/eclipse/emf/common/ui/viewer/ColumnResizer.java#L219

Changing the value to 20 works on Mac, but I don't know if there might be an underlying miscalculation from `TreeColumn#getWidth()`

**Comment by Phillipus** [comment]
The best I could come up with is:

```java
int width = packedColumnWidths.get(i) + (SWT.getPlatform().equals("cocoa") ? 28 : 10);
```

But seems a bit of a workaround.

**Comment by merks** [comment]
It does seem like a bit of a workaround...  

The 10 is just to add some padding on Windows so that it doesn't look like  this:

![image](https://github.com/eclipse-emf/org.eclipse.emf/assets/208716/51910f2b-8b91-4e36-a6bc-4e219387b791)

From your pictures it does look like a certain fixed amount is cropped from the end, so a constant that looks fine for you is probably fine.

I'll go with that...

**Comment by merks** [comment]
A nightly build is in progress.

**Comment by Phillipus** [comment]
@merks Thanks for your commit!

**Comment by merks** [comment]
Effective teamwork makes for fast results!  💯
