### ISSUE TITLE
Maven artifact org.eclipse.emf.ecore.xcore v1.27.0 is missing SLF4J dependency

### ISSUE THREAD

**Issue by janhicken** [eclipse-emf/org.eclipse.emf#21]
Since 2a566cd938c1a6e06b5054d154813f4677d3593e, SLF4J is used for logging. 

The corresponding dependency changes are reflected in the plugin's `MANIFEST.MF`, however, the necessary changes in the `pom.xml` are missing.

This results in a missing dependency when using v1.27.0 from Maven Central. 

Since I don't have SLF4J in my application's classpath, I get the following exceptions after updating:

```
java.lang.NoClassDefFoundError: org/slf4j/Logger
```

Could you adapt the `pom.xml` and add SLF4J as dependency?

**Comment by merks** [comment]
When the next release is published to Maven  in the beginning of March it will include such a dependency:

![image](https://github.com/eclipse-emf/org.eclipse.emf/assets/208716/e61adb70-b1ce-4303-9cbf-0238094b8fe9)

**Comment by merks** [comment]
This latest version 

https://repo1.maven.org/maven2/org/eclipse/emf/org.eclipse.emf.ecore.xcore/1.28.0/org.eclipse.emf.ecore.xcore-1.28.0.pom

Has the dependency, but it's kind of an out-dated version:  😢 

![image](https://github.com/eclipse-emf/org.eclipse.emf/assets/208716/e9f3fe04-a951-4cc2-97b9-e019c6ae718a)
