### ISSUE TITLE
EFactoryImpl cannot be resolved

### ISSUE THREAD

**Issue by jukzi** [eclipse-emf/org.eclipse.emf#41]
A fresh OOmphed platform workspace results in error in org.eclipse.ui.tests:
```
The project was not built since its build path is incomplete. Cannot find the class file for org.eclipse.emf.ecore.impl.EFactoryImpl. Fix the build path then try building this project

The type org.eclipse.emf.ecore.impl.EFactoryImpl cannot be resolved. It is indirectly referenced from required type org.eclipse.e4.ui.model.application.ui.menu.impl.MenuFactoryImpl
```
![image](https://github.com/user-attachments/assets/1d4cbfe2-04eb-468f-8ceb-21dd8c0b7ec4)

This can be solved by adding a Require-Bundle for org.eclipse.emf.ecore in eclipse.platform.ui\tests\org.eclipse.ui.tests\META-INF\MANIFEST.MF or 
visibility:=reexport for org.eclipse.emf.ecore;bundle-version="2.37.0" in eclipse.platform.ui\bundles\org.eclipse.e4.ui.model.workbench\META-INF\MANIFEST.MF
However i don't know how it broke or where it is supposed to be fixed.

**Comment by merks** [comment]
I fixed it like this:

![image](https://github.com/user-attachments/assets/90b87aec-1a08-44c6-ac45-ff076cc8a8ee)

I asked other people if they could reproduce this problem, but they couldn't.

Goodness knows what changed; something in JDT, or something along the dependency chain.   

In any case, that's the way to fix it, i.e., add a direct dependency on the thing JDT is complaining
