### ISSUE TITLE
Xtext usage in emf.core

### ISSUE THREAD

**Issue by Bananeweizen** [eclipse-emf/org.eclipse.emf#43]
Creating a workspace with emf-core only (without the other EMF project sub nodes) leads to unknown Xtext nature warnings:
![grafik](https://github.com/user-attachments/assets/c5629f83-9ea0-4c7d-8b53-d4538fd24408)

To me it looks like there are no Xtext extension points and no Xtext DSL files in those projects, but I'm not entirely sure. Happy to provide a removal patch, if you agree (or a setup change patch otherwise).

**Comment by merks** [comment]
I think those natures are needed when these models are used by Xcore so that the *.ecore/*.genmodel are properly indexed.   A preference task to turn off the errors would seem appropriate.  (I don't see such errors in the SDK workspace where org.eclipse.emf.ecore is also available as source.)

**Comment by Bananeweizen** [comment]
The issue is not valid. Due to your PR feedback I found that the emf.setup already disables the missing nature warning. But I had it enabled in my _personal_ setup, and therefore caused the errors myself. Sorry for the noise.

**Comment by merks** [comment]
No problem!  Thanks for trying to help.
